### ISSUE TITLE
Git branches are used incorrectly

### ISSUE THREAD

**Issue by rnfmcb** [Class41/ProjectLuna#2]
Git branches are used incorrectly. They should not be individual branches for people. If used appropriately, no need to depend as much on each other. 
![image](https://user-images.githubusercontent.com/28956082/44951125-80089500-ae21-11e8-9d4e-2b4c48719ce1.png)
See tutorial for instructions 
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by Class41** [comment]
I understand this and this was done on purpose to accommodate Brad. Art/large model files are not typically part of a program's development workflow and having to constantly pull large art files would be an inconvenience more than a blessing. Hence the art branch: so that brad can work on his art projects and have version control while not making us pull gigabit files every few hours. Art files are sometimes not written in a line-by-line basis and will require re-downloading the full file again and not just the section modified. The moonlight branch is the development branch. You may create your own branch for your development needs if you wish.

Nothing further.

**Comment by rnfmcb** [comment]
I personally would be embarrassed to show a teacher or employer an improperly formatted git tree with unprofessional names. Therefore, my branches will follow standard formatting and be named appropriately.

**Comment by Class41** [comment]
fixed
